Debugging SSL cert creation issues. Small changes.

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -6,7 +6,7 @@ services:
     setup:
         image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
         volumes:
-            - ./certs:/usr/share/elasticsearch/config/certs
+            - certs:/usr/share/elasticsearch/config/certs
         user: "0"
         command: >
             bash -c '
@@ -26,9 +26,9 @@ services:
                     echo "Creating certs";
                     echo -ne \
                     "instances:\n"\
-                    "  - name: elasticsearch\n"\
+                    "  - name: elas1\n"\
                     "    dns:\n"\
-                    "      - elasticsearch\n"\
+                    "      - elas1\n"\
                     "      - localhost\n"\
                     "    ip:\n"\
                     "      - 127.0.0.1\n"\
@@ -41,54 +41,54 @@ services:
                 find . -type d -exec chmod 750 \{\} \;;
                 find . -type f -exec chmod 640 \{\} \;;
                 echo "Waiting for Elasticsearch availability";
-                until curl -s --cacert config/certs/ca/ca.crt https://elasticsearch:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
+                until curl -s --cacert config/certs/ca/ca.crt https://elas1:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
                 echo "Setting kibana_system password";
-                until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD]}\"}" | grep -q "^{}"; do sleep 10; done;
+                until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://elas1:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
                 echo "All done!";
             '
         healthcheck:
-            test: ["CMD-SHELL", "[ -f config/certs/elasticsearch/elasticsearch.crt ]"]
+            test: ["CMD-SHELL", "[ -f config/certs/elas1/elas1.crt ]"]
             interval: 1s
             timeout: 5s
             retries: 120
 
-    elasticsearch:
+    elas1:
         depends_on:
             setup:
                 condition: service_healthy
         image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION} 
-        container_name: elasticsearch
+        container_name: elas1
         volumes:
-            - ./certs:/usr/share/elasticsearch/config/certs
-            - ./elasticsearch-volume:/usr/share/elasticsearch/data
+            - certs:/usr/share/elasticsearch/config/certs
+            - elasticsearch-volume:/usr/share/elasticsearch/data
         ports:
             - 9200:9200
         networks:
             - elastic-net
         # Health check to check that elasticsearch is fully up.
         healthcheck:
-            test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"] 
-            interval: 30s
-            timeout: 30s
-            retries: 2
+            test: ["CMD-SHELL", "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'"] 
+            interval: 10s
+            timeout: 10s 
+            retries: 120
         # We disable security for development purposes, so that we don't need authentication. Security should be enabled in PROD.
         # Single node to elect this node as master and to not join any other cluster.
         environment:
             #- xpack.security.enabled=false
             #- discovery.type=single-node
-            - node.name=es02
+            - node.name=elas1
             - cluster.name=${CLUSTER_NAME}
-            - cluster.initial_master_nodes=elasticsearch
-            #- discovery.seed_hosts=es01,es03
+            - cluster.initial_master_nodes=elas1
+            - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
             - bootstrap.memory_lock=true
             - xpack.security.enabled=true
             - xpack.security.http.ssl.enabled=true
-            - xpack.security.http.ssl.key=certs/elasticsearch/elasticsearch.key
-            - xpack.security.http.ssl.certificate=certs/elasticsearch/elasticsearch.crt
-            - xpack.security.http.ssl.certificate_authorities=certs/elasticsearch/elasticsearch.crt
+            - xpack.security.http.ssl.key=certs/elas1/elas1.key
+            - xpack.security.http.ssl.certificate=certs/elas1/elas1.crt
+            - xpack.security.http.ssl.certificate_authorities=certs/elas1/elas1.crt
             - xpack.security.transport.ssl.enabled=true
-            - xpack.security.transport.ssl.key=certs/elasticsearch/elasticsearch.key
-            - xpack.security.transport.ssl.certificate=certs/elasticsearch/elasticsearch.crt
+            - xpack.security.transport.ssl.key=certs/elas1/elas1.key
+            - xpack.security.transport.ssl.certificate=certs/elas1/elas1.crt
             - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
             - xpack.security.transport.ssl.verification_mode=certificate
             - xpack.license.self_generated.type=${LICENSE}
@@ -106,28 +106,28 @@ services:
     kibana:
         # The following will make sure that Kibana runs only after elasticsearch is up and healthy.
         depends_on:
-            elasticsearch:
+            elas1:
                 condition: service_healthy
-        image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION} 
+        image: docker.elastic.co/kibana/kibana:${STACK_VERSION} 
         container_name: kibana
         volumes:
-            - ./certs:/usr/share/kibana/config/certs
-            - ./kibana-volume:/usr/share/kibana/data
+            - certs:/usr/share/kibana/config/certs
+            - kibana-volume:/usr/share/kibana/data
         ports:
             - 5601:5601
         networks:
             - elastic-net
         environment:
             - SERVERNAME=kibana
-            - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
+            - ELASTICSEARCH_HOSTS=https://elas1:9200
             - ELASTICSEARCH_USERNAME=kibana_system
             - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
             - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
-        healthcheck:
-            test: curl --silent --fail localhost:5601/api/task_manager/_health || exit 1
-            interval: 30s
-            timeout: 30s
-            retries: 5
+        #healthcheck:
+            #test: curl --silent --fail localhost:5601/api/task_manager/_health || exit 1
+            #interval: 30s
+            #timeout: 30s
+            #retries: 5
         logging:
             driver: "local"
             options:
